project:
  type: website
  output-dir: docs

website:
  title: "Biochemistry Equations"
  site-url: https://biochemistry-equations.github.io/
  navbar:
    left:
      - text: "Chemical Kinetics"
        menu:
          - text: "Chemical Kinetics Overview"
            href: Chemical_Kinetics/index.html  
          - text: "Zero Order"
            href: Chemical_Kinetics/zero_order.html
          - text: "First Order"
            href: Chemical_Kinetics/first_order.html
          - text: "Second Order"
            href: Chemical_Kinetics/second_order.html
            
      - text: "Ligand Binding"
        menu:
          - text: "Ligand Binding Overview"
            href: Ligand_Binding/index.html  
          - text: "Hyperbola"
            href: Ligand_Binding/hyperbola.html
          - text: "Quadratic"
            href: Ligand_Binding/quadratic.html
      
      - text: "Drug Binding"
        menu:
          - text: "Drug Binding Overview"
            href: Drug_Binding/index.html  
          - text: "Cheng Prusoff"
            href: Drug_Binding/cheng_prusoff.html
          - text: "Munson Rodbard"
            href: Drug_Binding/munson_rodbard.html
          - text: "Motulsky Mahan"
            href: Drug_Binding/motulsky_mahan.html  
    
    right:
      - icon: github
        href: https://github.com/biochemistry-equations/biochemistry-equations.github.io
        aria-label: GitHub Repository
        
      - text: "About"
        href: about.html

format:
  html:
    theme:
      light: cosmo
      dark: slate
    toc: false
    toc-depth: 2
    code-fold: true
    smooth-scroll: true
    page-layout: article